{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "40286fb1-8583-49fc-af32-56f5d1a3310d",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "\n",
    "When creating a custom exception in Python, it is necessary to inherit from the Exception class. The Exception class serves as a base class for all built-in exceptions in Python, and it provides a standard interface for defining and handling exceptions.\n",
    "\n",
    "By inheriting from the Exception class, we can take advantage of its existing functionality, such as its ability to capture a traceback of the error, and its ability to provide a string representation of the exception through the __str__() method.\n",
    "\n",
    "Additionally, using the Exception class as the base class for our custom exception ensures that our exception follows the same interface as other built-in exceptions. This makes it easier for other developers to understand how to use and handle our custom exception, since they can rely on the same methods and properties that they are already familiar with.\n",
    "\n",
    "In summary, using the Exception class as the base class for our custom exception ensures that our exception follows a standard interface, provides useful functionality, and is easy to use and handle in the same way as other built-in exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "17a5b998-7ede-44b6-98bb-8060dd8159b5",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "Sure, here's a Python program that prints the Python Exception Hierarchy using the built-in Exception class:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2d58175c-3cc1-42b9-a299-dff8bcd1159e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'Exception'>\n",
      "    <class 'TypeError'>\n",
      "        <class 'decimal.FloatOperation'>\n",
      "        <class 'email.errors.MultipartConversionError'>\n",
      "    <class 'StopAsyncIteration'>\n",
      "    <class 'StopIteration'>\n",
      "    <class 'ImportError'>\n",
      "        <class 'ModuleNotFoundError'>\n",
      "        <class 'zipimport.ZipImportError'>\n",
      "    <class 'OSError'>\n",
      "        <class 'ConnectionError'>\n",
      "            <class 'BrokenPipeError'>\n",
      "            <class 'ConnectionAbortedError'>\n",
      "            <class 'ConnectionRefusedError'>\n",
      "            <class 'ConnectionResetError'>\n",
      "                <class 'http.client.RemoteDisconnected'>\n",
      "        <class 'BlockingIOError'>\n",
      "        <class 'ChildProcessError'>\n",
      "        <class 'FileExistsError'>\n",
      "        <class 'FileNotFoundError'>\n",
      "        <class 'IsADirectoryError'>\n",
      "        <class 'NotADirectoryError'>\n",
      "        <class 'InterruptedError'>\n",
      "            <class 'zmq.error.InterruptedSystemCall'>\n",
      "        <class 'PermissionError'>\n",
      "        <class 'ProcessLookupError'>\n",
      "        <class 'TimeoutError'>\n",
      "        <class 'io.UnsupportedOperation'>\n",
      "        <class 'signal.itimer_error'>\n",
      "        <class 'socket.herror'>\n",
      "        <class 'socket.gaierror'>\n",
      "        <class 'ssl.SSLError'>\n",
      "            <class 'ssl.SSLCertVerificationError'>\n",
      "            <class 'ssl.SSLZeroReturnError'>\n",
      "            <class 'ssl.SSLWantWriteError'>\n",
      "            <class 'ssl.SSLWantReadError'>\n",
      "            <class 'ssl.SSLSyscallError'>\n",
      "            <class 'ssl.SSLEOFError'>\n",
      "        <class 'shutil.Error'>\n",
      "            <class 'shutil.SameFileError'>\n",
      "        <class 'shutil.SpecialFileError'>\n",
      "        <class 'shutil.ExecError'>\n",
      "        <class 'shutil.ReadError'>\n",
      "        <class 'urllib.error.URLError'>\n",
      "            <class 'urllib.error.HTTPError'>\n",
      "            <class 'urllib.error.ContentTooShortError'>\n",
      "        <class 'gzip.BadGzipFile'>\n",
      "    <class 'EOFError'>\n",
      "        <class 'asyncio.exceptions.IncompleteReadError'>\n",
      "    <class 'RuntimeError'>\n",
      "        <class 'RecursionError'>\n",
      "        <class 'NotImplementedError'>\n",
      "            <class 'zmq.error.ZMQVersionError'>\n",
      "            <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "        <class '_frozen_importlib._DeadlockError'>\n",
      "        <class 'threading.BrokenBarrierError'>\n",
      "        <class 'concurrent.futures._base.BrokenExecutor'>\n",
      "            <class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "        <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "        <class 'pkg_resources.ExtractionError'>\n",
      "        <class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "    <class 'NameError'>\n",
      "        <class 'UnboundLocalError'>\n",
      "    <class 'AttributeError'>\n",
      "        <class 'dataclasses.FrozenInstanceError'>\n",
      "    <class 'SyntaxError'>\n",
      "        <class 'IndentationError'>\n",
      "            <class 'TabError'>\n",
      "    <class 'LookupError'>\n",
      "        <class 'IndexError'>\n",
      "        <class 'KeyError'>\n",
      "            <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "            <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "        <class 'encodings.CodecRegistryError'>\n",
      "    <class 'ValueError'>\n",
      "        <class 'UnicodeError'>\n",
      "            <class 'UnicodeEncodeError'>\n",
      "            <class 'UnicodeDecodeError'>\n",
      "            <class 'UnicodeTranslateError'>\n",
      "        <class 'io.UnsupportedOperation'>\n",
      "        <class 'json.decoder.JSONDecodeError'>\n",
      "        <class 'ssl.SSLCertVerificationError'>\n",
      "        <class 'binascii.Error'>\n",
      "        <class '_hashlib.UnsupportedDigestmodError'>\n",
      "        <class 'calendar.IllegalMonthError'>\n",
      "        <class 'calendar.IllegalWeekdayError'>\n",
      "        <class 'dateutil.parser._parser.ParserError'>\n",
      "        <class 'pygments.util.ClassNotFound'>\n",
      "        <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "        <class 'email.errors.MessageDefect'>\n",
      "            <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "            <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "            <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "            <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "            <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "            <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "            <class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "            <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "            <class 'email.errors.UndecodableBytesDefect'>\n",
      "            <class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "            <class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "            <class 'email.errors.InvalidBase64LengthDefect'>\n",
      "            <class 'email.errors.HeaderDefect'>\n",
      "                <class 'email.errors.InvalidHeaderDefect'>\n",
      "                <class 'email.errors.HeaderMissingRequiredValue'>\n",
      "                <class 'email.errors.NonPrintableDefect'>\n",
      "                <class 'email.errors.ObsoleteHeaderDefect'>\n",
      "                <class 'email.errors.NonASCIILocalPartDefect'>\n",
      "                <class 'email.errors.InvalidDateDefect'>\n",
      "        <class 'IPython.core.magics.code.MacroToEdit'>\n",
      "        <class 'plistlib.InvalidFileException'>\n",
      "        <class 'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "        <class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
      "        <class 'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "        <class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
      "        <class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
      "        <class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "        <class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
      "        <class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
      "        <class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "        <class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
      "            <class 'pkg_resources.RequirementParseError'>\n",
      "        <class 'packaging.version.InvalidVersion'>\n",
      "    <class 'AssertionError'>\n",
      "    <class 'ArithmeticError'>\n",
      "        <class 'FloatingPointError'>\n",
      "        <class 'OverflowError'>\n",
      "        <class 'ZeroDivisionError'>\n",
      "            <class 'decimal.DivisionByZero'>\n",
      "            <class 'decimal.DivisionUndefined'>\n",
      "        <class 'decimal.DecimalException'>\n",
      "            <class 'decimal.Clamped'>\n",
      "            <class 'decimal.Rounded'>\n",
      "                <class 'decimal.Underflow'>\n",
      "                <class 'decimal.Overflow'>\n",
      "            <class 'decimal.Inexact'>\n",
      "                <class 'decimal.Underflow'>\n",
      "                <class 'decimal.Overflow'>\n",
      "            <class 'decimal.Subnormal'>\n",
      "                <class 'decimal.Underflow'>\n",
      "            <class 'decimal.DivisionByZero'>\n",
      "            <class 'decimal.FloatOperation'>\n",
      "            <class 'decimal.InvalidOperation'>\n",
      "                <class 'decimal.ConversionSyntax'>\n",
      "                <class 'decimal.DivisionImpossible'>\n",
      "                <class 'decimal.DivisionUndefined'>\n",
      "                <class 'decimal.InvalidContext'>\n",
      "    <class 'SystemError'>\n",
      "        <class 'encodings.CodecRegistryError'>\n",
      "    <class 'ReferenceError'>\n",
      "    <class 'MemoryError'>\n",
      "    <class 'BufferError'>\n",
      "    <class 'Warning'>\n",
      "        <class 'UserWarning'>\n",
      "            <class 'getpass.GetPassWarning'>\n",
      "            <class 'IPython.core.formatters.FormatterWarning'>\n",
      "        <class 'EncodingWarning'>\n",
      "        <class 'DeprecationWarning'>\n",
      "            <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "        <class 'PendingDeprecationWarning'>\n",
      "        <class 'SyntaxWarning'>\n",
      "        <class 'RuntimeWarning'>\n",
      "            <class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "            <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "            <class 'pkg_resources.PEP440Warning'>\n",
      "        <class 'FutureWarning'>\n",
      "            <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "        <class 'ImportWarning'>\n",
      "        <class 'UnicodeWarning'>\n",
      "        <class 'BytesWarning'>\n",
      "        <class 'ResourceWarning'>\n",
      "        <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "        <class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
      "    <class 'warnings._OptionError'>\n",
      "    <class 'runpy._Error'>\n",
      "    <class 're.error'>\n",
      "    <class 'sre_parse.Verbose'>\n",
      "    <class 'locale.Error'>\n",
      "    <class 'subprocess.SubprocessError'>\n",
      "        <class 'subprocess.CalledProcessError'>\n",
      "        <class 'subprocess.TimeoutExpired'>\n",
      "    <class 'tokenize.TokenError'>\n",
      "    <class 'tokenize.StopTokenizing'>\n",
      "    <class 'inspect.ClassFoundException'>\n",
      "    <class 'inspect.EndOfBlock'>\n",
      "    <class 'traitlets.traitlets.TraitError'>\n",
      "    <class 'copy.Error'>\n",
      "    <class 'concurrent.futures._base.Error'>\n",
      "        <class 'concurrent.futures._base.CancelledError'>\n",
      "        <class 'concurrent.futures._base.TimeoutError'>\n",
      "        <class 'concurrent.futures._base.InvalidStateError'>\n",
      "    <class 'socket._GiveupOnSendfile'>\n",
      "    <class 'struct.error'>\n",
      "    <class 'binascii.Incomplete'>\n",
      "    <class 'asyncio.exceptions.TimeoutError'>\n",
      "    <class 'asyncio.exceptions.InvalidStateError'>\n",
      "    <class 'asyncio.exceptions.LimitOverrunError'>\n",
      "    <class 'asyncio.queues.QueueEmpty'>\n",
      "    <class 'asyncio.queues.QueueFull'>\n",
      "    <class '_queue.Empty'>\n",
      "    <class 'queue.Full'>\n",
      "    <class 'ctypes.ArgumentError'>\n",
      "    <class 'zmq.error.ZMQBaseError'>\n",
      "        <class 'zmq.error.ZMQError'>\n",
      "            <class 'zmq.error.ContextTerminated'>\n",
      "            <class 'zmq.error.Again'>\n",
      "            <class 'zmq.error.InterruptedSystemCall'>\n",
      "        <class 'zmq.error.ZMQBindError'>\n",
      "        <class 'zmq.error.NotDone'>\n",
      "    <class '_pickle.PickleError'>\n",
      "        <class '_pickle.PicklingError'>\n",
      "        <class '_pickle.UnpicklingError'>\n",
      "    <class 'pickle._Stop'>\n",
      "    <class 'argparse.ArgumentError'>\n",
      "    <class 'argparse.ArgumentTypeError'>\n",
      "    <class 'traitlets.config.loader.ConfigError'>\n",
      "        <class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "            <class 'traitlets.config.loader.ArgumentError'>\n",
      "        <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "    <class 'traitlets.config.configurable.ConfigurableError'>\n",
      "        <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "    <class 'traitlets.config.application.ApplicationError'>\n",
      "    <class 'zlib.error'>\n",
      "    <class 'tornado.util.TimeoutError'>\n",
      "    <class '_curses.error'>\n",
      "    <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "    <class 'tornado.gen.KeyReuseError'>\n",
      "    <class 'tornado.gen.UnknownKeyError'>\n",
      "    <class 'tornado.gen.LeakedCallbackError'>\n",
      "    <class 'tornado.gen.BadYieldError'>\n",
      "    <class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "    <class 'tornado.gen.Return'>\n",
      "    <class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "    <class 'termios.error'>\n",
      "    <class '_lzma.LZMAError'>\n",
      "    <class 'shutil.RegistryError'>\n",
      "    <class 'shutil._GiveupOnFastCopy'>\n",
      "    <class 'configparser.Error'>\n",
      "        <class 'configparser.NoSectionError'>\n",
      "        <class 'configparser.DuplicateSectionError'>\n",
      "        <class 'configparser.DuplicateOptionError'>\n",
      "        <class 'configparser.NoOptionError'>\n",
      "        <class 'configparser.InterpolationError'>\n",
      "            <class 'configparser.InterpolationMissingOptionError'>\n",
      "            <class 'configparser.InterpolationSyntaxError'>\n",
      "            <class 'configparser.InterpolationDepthError'>\n",
      "        <class 'configparser.ParsingError'>\n",
      "            <class 'configparser.MissingSectionHeaderError'>\n",
      "    <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "    <class 'zipfile.BadZipFile'>\n",
      "    <class 'zipfile.LargeZipFile'>\n",
      "    <class 'entrypoints.BadEntryPoint'>\n",
      "    <class 'entrypoints.NoSuchEntryPoint'>\n",
      "    <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "    <class 'pydoc.ErrorDuringImport'>\n",
      "    <class 'executing.executing.NotOneValueFound'>\n",
      "    <class 'pure_eval.utils.CannotEval'>\n",
      "    <class 'pygments.util.OptionError'>\n",
      "    <class 'bdb.BdbQuit'>\n",
      "    <class 'pdb.Restart'>\n",
      "    <class 'pexpect.exceptions.ExceptionPexpect'>\n",
      "        <class 'pexpect.exceptions.EOF'>\n",
      "        <class 'pexpect.exceptions.TIMEOUT'>\n",
      "    <class 'ptyprocess.util.PtyProcessError'>\n",
      "    <class 'IPython.utils.process.FindCmdError'>\n",
      "    <class 'IPython.utils.path.HomeDirError'>\n",
      "    <class 'IPython.core.profiledir.ProfileDirError'>\n",
      "    <class 'IPython.core.error.IPythonCoreError'>\n",
      "        <class 'IPython.core.error.TryNext'>\n",
      "        <class 'IPython.core.error.UsageError'>\n",
      "        <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "    <class 'IPython.core.error.InputRejected'>\n",
      "    <class 'getopt.GetoptError'>\n",
      "    <class 'pygments.filters.ErrorToken'>\n",
      "    <class 'IPython.core.prefilter.PrefilterError'>\n",
      "    <class 'IPython.core.alias.AliasError'>\n",
      "        <class 'IPython.core.alias.InvalidAliasError'>\n",
      "    <class 'sqlite3.Error'>\n",
      "        <class 'sqlite3.InterfaceError'>\n",
      "        <class 'sqlite3.DatabaseError'>\n",
      "            <class 'sqlite3.InternalError'>\n",
      "            <class 'sqlite3.OperationalError'>\n",
      "            <class 'sqlite3.ProgrammingError'>\n",
      "            <class 'sqlite3.IntegrityError'>\n",
      "            <class 'sqlite3.DataError'>\n",
      "            <class 'sqlite3.NotSupportedError'>\n",
      "    <class 'sqlite3.Warning'>\n",
      "    <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "    <class 'xml.dom.DOMException'>\n",
      "        <class 'xml.dom.IndexSizeErr'>\n",
      "        <class 'xml.dom.DomstringSizeErr'>\n",
      "        <class 'xml.dom.HierarchyRequestErr'>\n",
      "        <class 'xml.dom.WrongDocumentErr'>\n",
      "        <class 'xml.dom.InvalidCharacterErr'>\n",
      "        <class 'xml.dom.NoDataAllowedErr'>\n",
      "        <class 'xml.dom.NoModificationAllowedErr'>\n",
      "        <class 'xml.dom.NotFoundErr'>\n",
      "        <class 'xml.dom.NotSupportedErr'>\n",
      "        <class 'xml.dom.InuseAttributeErr'>\n",
      "        <class 'xml.dom.InvalidStateErr'>\n",
      "        <class 'xml.dom.SyntaxErr'>\n",
      "        <class 'xml.dom.InvalidModificationErr'>\n",
      "        <class 'xml.dom.NamespaceErr'>\n",
      "        <class 'xml.dom.InvalidAccessErr'>\n",
      "        <class 'xml.dom.ValidationErr'>\n",
      "    <class 'prompt_toolkit.validation.ValidationError'>\n",
      "    <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "    <class 'prompt_toolkit.buffer._Retry'>\n",
      "    <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "    <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "    <class 'parso.parser.ParserSyntaxError'>\n",
      "    <class 'parso.parser.InternalParseError'>\n",
      "    <class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "    <class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "    <class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "    <class 'jedi.inference.base_value.HasNoContext'>\n",
      "    <class 'jedi.inference.arguments.ParamIssue'>\n",
      "    <class 'jedi.api.exceptions._JediError'>\n",
      "        <class 'jedi.api.exceptions.InternalError'>\n",
      "        <class 'jedi.api.exceptions.WrongVersion'>\n",
      "        <class 'jedi.api.exceptions.RefactoringError'>\n",
      "    <class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "    <class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "    <class 'email.errors.MessageError'>\n",
      "        <class 'email.errors.MessageParseError'>\n",
      "            <class 'email.errors.HeaderParseError'>\n",
      "            <class 'email.errors.BoundaryError'>\n",
      "        <class 'email.errors.MultipartConversionError'>\n",
      "        <class 'email.errors.CharsetError'>\n",
      "    <class 'uu.Error'>\n",
      "    <class 'http.client.HTTPException'>\n",
      "        <class 'http.client.NotConnected'>\n",
      "        <class 'http.client.InvalidURL'>\n",
      "        <class 'http.client.UnknownProtocol'>\n",
      "        <class 'http.client.UnknownTransferEncoding'>\n",
      "        <class 'http.client.UnimplementedFileMode'>\n",
      "        <class 'http.client.IncompleteRead'>\n",
      "        <class 'http.client.ImproperConnectionState'>\n",
      "            <class 'http.client.CannotSendRequest'>\n",
      "            <class 'http.client.CannotSendHeader'>\n",
      "            <class 'http.client.ResponseNotReady'>\n",
      "        <class 'http.client.BadStatusLine'>\n",
      "            <class 'http.client.RemoteDisconnected'>\n",
      "        <class 'http.client.LineTooLong'>\n",
      "    <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "    <class 'IPython.terminal.embed.KillEmbedded'>\n",
      "    <class 'psutil.Error'>\n",
      "        <class 'psutil.NoSuchProcess'>\n",
      "            <class 'psutil.ZombieProcess'>\n",
      "        <class 'psutil.AccessDenied'>\n",
      "        <class 'psutil.TimeoutExpired'>\n",
      "    <class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
      "    <class 'tornado.queues.QueueEmpty'>\n",
      "    <class 'tornado.queues.QueueFull'>\n",
      "    <class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
      "    <class 'xml.parsers.expat.ExpatError'>\n",
      "    <class 'xmlrpc.client.Error'>\n",
      "        <class 'xmlrpc.client.ProtocolError'>\n",
      "        <class 'xmlrpc.client.ResponseError'>\n",
      "        <class 'xmlrpc.client.Fault'>\n",
      "    <class 'pkg_resources._vendor.pyparsing.exceptions.ParseBaseException'>\n",
      "        <class 'pkg_resources._vendor.pyparsing.exceptions.ParseException'>\n",
      "        <class 'pkg_resources._vendor.pyparsing.exceptions.ParseFatalException'>\n",
      "            <class 'pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException'>\n",
      "    <class 'pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException'>\n",
      "    <class 'pkg_resources.ResolutionError'>\n",
      "        <class 'pkg_resources.VersionConflict'>\n",
      "            <class 'pkg_resources.ContextualVersionConflict'>\n",
      "        <class 'pkg_resources.DistributionNotFound'>\n",
      "        <class 'pkg_resources.UnknownExtra'>\n",
      "    <class '_pydevd_bundle.pydevd_runpy._Error'>\n",
      "    <class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "    <class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n"
     ]
    }
   ],
   "source": [
    "# Python program to print Python Exception Hierarchy\n",
    "\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    \"\"\"Prints the exception hierarchy starting from the given class\"\"\"\n",
    "    print(' ' * indent + str(exception_class))\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent+4)\n",
    "\n",
    "# Print the exception hierarchy starting from the base Exception class\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "979e11a9-0ccd-47a1-ae72-746af12eefc3",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "he ArithmeticError class is a built-in Python class that serves as the base class for all arithmetic errors. It is a subclass of the Exception class and is raised when an error occurs during an arithmetic operation.\n",
    "\n",
    "Some of the errors that are defined in the ArithmeticError class include:\n",
    "\n",
    "ZeroDivisionError: This error occurs when a number is divided by zero. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cd15dfec-d95f-4890-8e91-606ff81c6fb4",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m10\u001b[39m\n\u001b[1;32m      2\u001b[0m b \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[0;32m----> 3\u001b[0m c \u001b[38;5;241m=\u001b[39m \u001b[43ma\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mb\u001b[49m   \u001b[38;5;66;03m# ZeroDivisionError: division by zero\u001b[39;00m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "a = 10\n",
    "b = 0\n",
    "c = a / b   # ZeroDivisionError: division by zero\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28fd7c39-50c9-4795-ab4d-247ae39ca989",
   "metadata": {},
   "source": [
    "OverflowError: This error occurs when the result of an arithmetic operation is too large to be represented in the available memory. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "822d79a3-1cf8-4439-90b4-5c56bc8c0c54",
   "metadata": {},
   "outputs": [
    {
     "ename": "OverflowError",
     "evalue": "math range error",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOverflowError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmath\u001b[39;00m\n\u001b[0;32m----> 3\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[43mmath\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexp\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m1000\u001b[39;49m\u001b[43m)\u001b[49m   \u001b[38;5;66;03m# OverflowError: math range error\u001b[39;00m\n",
      "\u001b[0;31mOverflowError\u001b[0m: math range error"
     ]
    }
   ],
   "source": [
    "import math\n",
    "\n",
    "a = math.exp(1000)   # OverflowError: math range error\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a976ddd6-1f56-4839-ab80-3ebc9d4fa2ee",
   "metadata": {},
   "source": [
    "In this example, we are using the math.exp() function to calculate the exponential value of 1000. However, since the result is too large to be represented in the available memory, an OverflowError is raised."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1512ea86-46c4-4d87-871f-82bcbe75660f",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "The LookupError class is a built-in Python class that serves as the base class for all lookup errors. It is a subclass of the Exception class and is raised when a key or index lookup fails for a mapping or sequence type.\n",
    "\n",
    "Two common subclasses of the LookupError class are KeyError and IndexError.\n",
    "\n",
    "KeyError: This error occurs when a dictionary key or a set element is not found. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a311dfab-12da-4684-b969-52efdc900215",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'d'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m my_dict \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m'\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m1\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m2\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mc\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m3\u001b[39m}\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_dict\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43md\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m)   \u001b[38;5;66;03m# KeyError: 'd' not found in my_dict\u001b[39;00m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'd'"
     ]
    }
   ],
   "source": [
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "print(my_dict['d'])   # KeyError: 'd' not found in my_dict\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "deb3947d-d727-4aaa-acb4-ab20eb5fd2c2",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m## IndexError: This error occurs when an index is out of range for a sequence, such as a list or a tuple. For example\u001b[39;00m\n\u001b[1;32m      3\u001b[0m my_list \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m, \u001b[38;5;241m3\u001b[39m]\n\u001b[0;32m----> 4\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_list\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m]\u001b[49m)   \u001b[38;5;66;03m# IndexError: list index out of range\u001b[39;00m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "## IndexError: This error occurs when an index is out of range for a sequence, such as a list or a tuple. For example\n",
    "\n",
    "my_list = [1, 2, 3]\n",
    "print(my_list[3])   # IndexError: list index out of range\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "29c85e1e-94fb-40ee-882a-3a8076e518a2",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "\n",
    "ImportError is a built-in Python exception that is raised when a module is imported, but it cannot be found or loaded. This can occur if the module is not installed, if the file containing the module does not exist or is not readable, or if there is an error in the module code.\n",
    "\n",
    "Here's an example of how an ImportError can be raised:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d1365d09-ced7-424e-a9e7-2d472de5ed3e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Error: Module not found\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "daebb4b6-a59a-4199-aea5-94ab85dba595",
   "metadata": {},
   "source": [
    "ModuleNotFoundError is a subclass of ImportError that was introduced in Python 3.6. It is raised when a module cannot be found, similar to an ImportError. However, unlike ImportError, ModuleNotFoundError is only raised when the module is not found and cannot be located in any of the search paths.\n",
    "\n",
    "Here's an example of how a ModuleNotFoundError can be raised:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "b20de744-18c6-4664-8f9b-f5953145788d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"Error: Module not found\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca5c0528-5c4f-4716-9dc3-bb64b22d5f4a",
   "metadata": {},
   "source": [
    "In summary, both ImportError and ModuleNotFoundError are raised when a module cannot be imported. However, ModuleNotFoundError is a more specific subclass of ImportError that is only raised when the module cannot be found in any of the search paths."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "265d45db-d1f6-4207-b1b0-fd4edd9201d9",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "Here are some best practices for exception handling in Python:\n",
    "\n",
    "Be specific: Catch only the exceptions that you are expecting and handle them appropriately. Do not use a bare except clause unless you really need to catch all possible exceptions.\n",
    "\n",
    "Keep it simple: Keep your exception handling code as simple as possible. Avoid complex nested try-except blocks that can make it difficult to understand the flow of your code.\n",
    "\n",
    "Handle exceptions as close to the source as possible: Catch exceptions as close to the source of the error as possible. This will help you to isolate and fix the problem quickly.\n",
    "\n",
    "Use finally: Always use a finally block to ensure that any resources that were opened in a try block are properly closed or released, regardless of whether an exception was raised or not.\n",
    "\n",
    "Provide useful error messages: When raising an exception or printing an error message, be as descriptive as possible. This will help users to understand what went wrong and how to fix it.\n",
    "\n",
    "Avoid swallowing exceptions: Avoid catching an exception and doing nothing with it. If you catch an exception, either handle it appropriately or re-raise it so that it can be handled further up the call stack.\n",
    "\n",
    "Use context managers: Use context managers, such as the with statement, to ensure that resources are properly acquired and released. This can help to avoid common errors, such as leaving a file open after it has been read or written to.\n",
    "\n",
    "Use logging: Use the logging module to log exceptions and other error messages. This can be very helpful in diagnosing problems in production code.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6de5f1d0-5a1e-4254-bab0-bb197347f90d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
